from django.urls import path
from.import views

urlpatterns = [
    path('user_home', views.user_home, name = 'user_home'),
    path('user_login', views.user_login, name = 'user_login'),
    path('user_logout', views.user_logout, name = 'user_logout'),
    path('user_signup', views.user_signup, name = 'user_signup'),
    path('user_table', views.user_table, name = 'user_table'),
    path('user_delete\<int:id>', views.user_delete, name = 'user_delete'),
    path('user_update\<int:id>', views.user_update, name = 'user_update'),
    path('librarian_home', views.librarian_home, name = 'librarian_home'),
    path('librarian_login', views.librarian_login, name = 'librarian_login'),
    path('librarian_logout', views.librarian_logout, name = 'librarian_logout'),
    path('librarian_signup', views.librarian_signup, name = 'librarian_signup'),
    path('librarian_table', views.librarian_table, name = 'librarian_table'),
    path('librarian_delete\<int:id>', views.librarian_delete, name = 'librarian_delete'),
    path('librarian_update\<int:id>', views.librarian_update, name = 'librarian_update'),
    path('admin_home', views.admin_home, name = 'admin_home'),
    path('admin_login', views.admin_login, name = 'admin_login'),
    path('admin_signup', views.admin_signup, name = 'admin_signup'),
    path('admin_table', views.admin_table, name = 'admin_table'),
    path('admin_delete\<int:id>', views.admin_delete, name = 'admin_delete'),
    path('admin_update\<int:id>', views.admin_update, name = 'admin_update'),
    path('admin_logout', views.admin_logout, name = 'admin_logout'),
    path('add_books', views.add_books, name = 'add_books'),
    path('user_books', views.user_books, name = 'user_books'),
    path('librarian_books', views.librarian_books, name = 'librarian_books'),
    path('book_table', views.book_table, name = 'book_table'),
    path('book_delete/<int:id>', views.book_delete, name = 'book_delete'),
    path('book_update/<int:id>', views.book_update, name = 'book_update'),
    path('buyer', views.buyer, name = 'buyer'),
    path('order', views.order, name = 'order'),
    path('buyer_table', views.buyer_table, name = 'buyer_table'),
    path('buyer_delete/<int:id>', views.buyer_delete, name = 'buyer_delete'),
    path('buyer_update/<int:id>', views.buyer_update, name = 'buyer_update'),
    path('return_book', views.return_book, name = 'return_book'),
    path('return_success', views.return_success, name = 'return_success'),
    path('return_table', views.return_table, name = 'return_table'),
    path('return_delete/<int:id>', views.return_delete, name = 'return_delete'),
    path('return_update/<int:id>', views.return_update, name = 'return_update'),
    path('message', views.message, name = 'message'),
    path('admin_notification', views.admin_notification, name = 'admin_notification'),
    path('user_notification', views.user_notification, name = 'user_notification'),
    path('librarian_notification', views.librarian_notification, name = 'librarian_notification'),
    path('message_table', views.message_table, name = 'message_table'),
    path('message_delete/<int:id>', views.message_delete, name = 'message_delete'),
    path('main_home', views.main_home, name = 'main_home'),
    path('contact_table', views.contact_table, name = 'contact_table'),
    path('contact_delete/<int:id>', views.contact_delete, name = 'contact_delete'),



]