# Generated by Django 4.0.1 on 2023-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('day', models.TextField(max_length=50)),
                ('month', models.TextField(max_length=50)),
                ('year', models.TextField(max_length=50)),
                ('gender', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('cpassword', models.TextField(max_length=50)),
            ],
        ),
    ]
