# Generated by Django 4.0.1 on 2023-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraapp', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('price', models.TextField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
