# Generated by Django 4.0.1 on 2023-08-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraapp', '0004_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
