# Generated by Django 4.0.1 on 2023-08-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraapp', '0005_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=50)),
                ('price', models.TextField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
