# Generated by Django 4.0.1 on 2023-09-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraapp', '0006_books_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('book', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=100)),
                ('purchase_date', models.TextField(max_length=100)),
                ('return_date', models.TextField(max_length=100)),
                ('return_policy', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='books_data',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
