# Generated by Django 4.0.1 on 2023-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraapp', '0007_buyer_alter_books_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('book', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=100)),
                ('purchase_date', models.TextField(max_length=100)),
                ('return_date', models.TextField(max_length=100)),
                ('return_policy', models.TextField(max_length=100)),
            ],
        ),
    ]
