# Generated by Django 4.0.1 on 2023-09-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraapp', '0008_return_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
